### ISSUE TITLE
Generic cryptographic device with a PKCS#11 interface

### ISSUE THREAD

**Issue by fire** [nerves-hub/nerves_key#51]
Both https://shop.nitrokey.com/shop/product/nk-hsm-2-nitrokey-hsm-2-7 and https://github.com/opendnssec/SoftHSMv2 should be usable with nerves.

Usecase: instead of using nerveskey, once should be able to use a standard HSM module to act as a certificate authority and to sign keys.

I'm not sure of the status of this. Apologies if this is the wrong place.

**Comment by fire** [comment]
Apparently you can move this issue to https://github.com/nerves-hub/nerves_key_pkcs11.

**Comment by fhunleth** [comment]
The NervesKey isn't intended for acting as a certificate authority and signing keys. It's for holding the private key so that you can authenticate with a server, like AWS IoT or NervesHub. The chip that's used in the NervesKey has limited memory, so it's not going to be as nice as those links. On the other hand, the chip costs less than $1 and is really small.

Nerves and NervesHub don't prevent you from using an HSM. If you want to use one of those devices, don't use this project. Instead, use Erlang's PKCS#11 support and pass custom `ssl` options to the APIs that need to use the device. See the [Erlang Engine docs](https://erlang.org/doc/apps/crypto/engine_keys.html) for details. I'd recommend trying this on a Linux or Mac computer first before trying it out on Nerves.
