### ISSUE TITLE
ATECC608A - Status: Not Recommended for new designs

### ISSUE THREAD

**Issue by ahsf** [nerves-hub/nerves_key#60]
are there any plans to adapt ATECC608B for nerves-key?

https://www.microchip.com/wwwproducts/ProductCompare/ATECC608A/ATECC608B

**Comment by ahsf** [comment]
the migration guide claims, that timing issues could be avoiding by using the latest microship CryptoAuthLib.
As it seems nerves_key does not use hat lib but an elixir-port, right? (why?)

**Comment by fhunleth** [comment]
I wouldn't characterize this as a big issue. IMHO, the timing parts are to avoid unnecessary polling and to know when to quit. I.e., if it operation takes 500 ms, there's no reason to ask if it's done until 500 ms has passed since you already know the answer. If you ask at 400 ms, I don't think that's a big deal. The code is going to poll the device until it gets an answer and with the 608B, I'd just do a review of the operations in case the "give up" time is too short.

I feel like this is personal preference. The I2C messages aren't all that complicated so it was easier for me to do this in Elixir. I'm sure it could be done in C as well. Mostly, I had a failed attempted at getting the C version working two years ago and I sent a trivial PR to them that was ignored. Plus handling x509 certs is soooo much nicer in Elixir.
